### ISSUE TITLE
Cannot run Airconnect once its installed on Synology 2 bay NAS DiskStation DS218j

### ISSUE THREAD

**Issue by mikebreeezy** [eizedev/AirConnect-Synology#125]
I've tried installing and running the armv7 and armv7 static versions however I'm unable to airplay to my google speakers.

When I test airconnect on my windows PC, everything works fine. Please see the log attached:

[airconnect.log](https://github.com/user-attachments/files/16822536/airconnect.log)

**Comment by eizedev** [comment]
Hey @mikebreeezy i'm sorry to say, but your ds218j is too old to work with newer AirConnect versions since the redesign from version 1.0 and following versions. For more details please read this thread: https://github.com/eizedev/AirConnect-Synology/issues/63#issuecomment-1887246785
(the link will guide you to the comment with a solution for your device (use an older version of AirConnect-Synology)).
