### ISSUE TITLE
Failed to run

### ISSUE THREAD

**Issue by vespino** [eizedev/AirConnect-Synology#5]
I have 4 Nest Minis on my network, still Synology resports the package can't be run and tells me to make sure I have at least one Chromecast device on my network. Any tips on how to debug this and get things running?

**Comment by vespino** [comment]
Fiddling with IGMP snooping miraculously got it to work.

**Comment by eizedev** [comment]
Since many people have problems with the multicast configuration (especially IGMP snooping and IGMP proxy configuration), I have included a short chapter in the readme, which refers to it and gives some tips. In the beginning I also had these problems

[Multicast and IGMP Snooping/Proxy](https://github.com/eizedev/AirConnect-Synology/blob/master/README.md#multicast-and-igmp-snoopingproxy)

**Comment by vespino** [comment]
@eizedev great! I'm currently using Audio Station to play to my Next Minis, but it is possible to airplay streaming audio (so an internet stream) from the command line without the need of Audio Station?

**Comment by eizedev** [comment]
Unfortunately, I don't quite understand your question. From where would you like to play an audio stream? Because you write commandline -> From the Synology NAS locally? If you use AirPlay, you can of course use your IPhone to send a stream via AirPlay to a Sonos speaker. Or are you looking for something permanent that doesn't depend on your mobile phone?

If i start Audio Station (Playlist randomly chosen ;-)) i can select the "new" AirPlay speakers from AirConnect (Check the + symbol at the end of the name).
Sorry for the german language in the screenshot ;-) But most of it is self explaining:

![image](https://user-images.githubusercontent.com/6794362/97862805-41730b80-1d06-11eb-8ae1-48099a7fb20b.png)

**Comment by vespino** [comment]
I would like to initiate AirPlay from the Synology command line if possible. I'm currently using is as displayed in your screenshot. I'm Dutch, so don't worry, I can read fine :)

**Comment by eizedev** [comment]
hmm... good question. I found this thread online, but didnt't test it yet. So you can call a cgi from audiostation with some parameters: https://community.synology.com/enu/forum/17/post/16865?page=1&sort=oldest

newer post is about the player "mplayer" that audio station uses. You can call mplayer from the commandline: https://www.tutorialfor.com/questions-14505.htm

Also there exists a few command line "airplayer" link this one (written in ruby): https://coderwall.com/p/tpjlcw/command-line-airplay-video-client-for-appletv

Perhaps something works?

**Comment by vespino** [comment]
Thanks, I will look into those posts.
