### ISSUE TITLE
Update 1.0.13-20221216 not working in iTunes on Windows 11

### ISSUE THREAD

**Issue by Spy-1** [eizedev/AirConnect-Synology#66]
[airconnect.log](https://github.com/eizedev/AirConnect-Synology/files/10712972/airconnect.log)
updatetd to 1.0.13-20221216 
can not stream from iTunes/Win 11 to my sonos
Streaming from iPhone/iPad working.

0.2.51.2-20220206 worked in iTunes.
After downgrading 0.2.51.2-20220206 to it no longer works either.

**Comment by eizedev** [comment]
Hi @Spy-1 
we had a similar problem about 2 years ago, see https://github.com/eizedev/AirConnect-Synology/issues/12#issuecomment-877780211

the `--noflush` could perhaps help. The log you just uploaded seems to be fine. 

If nothing helps, could you please open a issue at the official [`AirConnect`](https://github.com/philippe44/AirConnect/issues) repository? I do not think the problem is related to the Synology package.

**Comment by Spy-1** [comment]
Hello Rene,
the problem is solved.
It was a firewall problem.
A switch from public to private network was the solution.
Greetings
Peter
